### ISSUE TITLE
physfs

### ISSUE THREAD

**Issue by gbbnfhb** [vitasdk/packages#154]
/home/a/vdpm/packages/physfs/src/physfs-3.0.2/src/physfs_platform_vita.c:160:13: error: too many arguments to function 'sceIoSyncByFd'
  160 |     BAIL_IF(sceIoSyncByFd(fd, 0) < 0, PHYSFS_ERR_IO, 0);

**Comment by isage** [comment]
You're using old version of vitasdk.

**Comment by gbbnfhb** [comment]
sorry,thanks
