### ISSUE TITLE
pixman.tar.xz package in Release is broken

### ISSUE THREAD

**Issue by ppiecuch** [vitasdk/packages#175]
Displays:

<Error><Code>NotFound</Code><Message>NotFound: Not Found&#xA;&#x9;status code: 404, request id: PR1KE14JR75D1GS3, host id: EH2agmPpgyRYsUys3IY+eNleB0zuLevsk0GCulnL5vc9+H+4gXxcxfOPbLb3mp0VhJ+gSNq/3vs=</Message><Resource>github-production-release-asset-2e65be76651657/1b42a85a-3f5b-46a7-915e-9386c4b793b0</Resource></Error>

**Comment by fish47** [comment]
same here
```xml
<Error>
    <Code>NotFound</Code>
    <Message>
        NotFound: Not Found
        status code: 404, 
        request id: 8QN3FCQP7F3MRP70, 
        host id: o6LJDOl/+pQY7IYMnIeg5GDANOVv2Hak5XfysERuUPFgHRZIo16tNX82HJTP8priMGq1poJ6+cw=
    </Message>
    <Resource>github-production-release-asset-2e65be76651657/1b42a85a-3f5b-46a7-915e-9386c4b793b0</Resource>
</Error>
```

**Comment by isage** [comment]
@d3m3vilurr afair, need to remove it from release first (because it's there, but throws 404. some github or upload-release-action bug)

**Comment by d3m3vilurr** [comment]
build seems restored now.
https://github.com/vitasdk/packages/actions/runs/1661814038 resolved?

**Comment by ppiecuch** [comment]
Yes, it works now - thank you!
