### ISSUE TITLE
opensles depends on sdl

### ISSUE THREAD

**Issue by v-atamanenko** [vitasdk/packages#203]
opensles actually depends on SDL too. I'm not sure though SDL1 or SDL2 or any of those. if you guys can, please add it as dependency in PKGBUILD. cc @Rinnegatamante

**Comment by isage** [comment]
It isn't (well, shouldn't): https://github.com/frangarcj/opensles/commit/05835dd48e652b170afee2fc94c628bc14be8aea

**Comment by v-atamanenko** [comment]
> It isn't (well, shouldn't): [frangarcj/opensles@05835dd](https://github.com/frangarcj/opensles/commit/05835dd48e652b170afee2fc94c628bc14be8aea)
Shouldn't, but is :)
```bash
$ grep -r "#include <SDL" .    
./sles_allinclusive.h:#include <SDL/SDL_audio.h>
```
So it's more like the issue in the respective repo? Should I go and make an issue there?

**Comment by isage** [comment]
Yup

**Comment by d3m3vilurr** [comment]
@v-atamanenko your project may have defined `USE_SDL` in somewhere.
https://github.com/frangarcj/opensles/blob/97d8efb/libopensles/sles_allinclusive.h#L67-L69

**Comment by v-atamanenko** [comment]
@d3m3vilurr well, actually, https://github.com/frangarcj/opensles/blob/97d8efbafd54530236e399e7278ba56fb9b5424b/libopensles/Makefile#L45

**Comment by d3m3vilurr** [comment]
it should fix in the `opensles` side. @frangarcj 
imo, this project removed every points of sdl function, so it wouldn't make the error when linking time.

@v-atamanenko so, if you have the `.a` file and `header`, you could be defined `USE_SDL` in somewhere
btw still you are right. when we make the package of `opensles`, we must have `sdl_audio` for including sdl header file evenif we don't use it
so, you can contribute opensles through making the patch of this. :)
