### ISSUE TITLE
Latest version of FluidLite uses incompatible relocations

### ISSUE THREAD

**Issue by lephilousophe** [vitasdk/packages#231]
Since commit aacbb3b159f0d658fde2336ea4fedae082b16ac5 FluidLite has been upgraded to a new version.
This new version includes a revamped CMakeLists.txt which forcibly sets POSITION_INDEPENDENT_CODE property on compiled objects.
Produced objects then contain relocations of type R_ARM_BASE_PREL (25) and R_ARM_GOT_BREL (26).
When linking code with FluidLite, vita-elf-create complains: `vita-elf-create: Invalid relocation type 25!`

I am not sure how this can be fixed without removing the faulty line in upstream CMakeLists.txt.

**Comment by Rinnegatamante** [comment]
I've actually tried to manually compile FluidLite without POSITION_INDEPENDENT_CODE property set and i still get a lib file that when linked gives the same exact error. Are we sure it's related to that property in particular?

**Comment by lephilousophe** [comment]
Thanks for the fix it works perfectly now.
I opened a PR upstream: https://github.com/divideconcept/FluidLite/pull/41

**Comment by lephilousophe** [comment]
The PR got merged
