### ISSUE TITLE
kuio no longer present in latest release, causing failing VDPM install.

### ISSUE THREAD

**Issue by YourWishes** [vitasdk/packages#258]
During the install of VDPM from the following script;
https://github.com/vitasdk/vdpm/blob/master/vdpm

Install is failing currently due to missing kuio.tar.xz in latest release. See example output from our CI/CD during latest builds;
```
find: ‘/tmp/vdpm_install_kuio’: No such file or directory
Installing kuio...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     74      0 --:--:-- --:--:-- --:--:--    75
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Was present a few hours ago when we ran test builds, but has been missing for a couple of hours.

Possible duplicates:
https://github.com/vitasdk/vdpm/issues/97
https://github.com/vitasdk/vdpm/issues/95
https://github.com/vitasdk/vdpm/issues/94

**Comment by isage** [comment]
Duplicate of https://github.com/vitasdk/vdpm/issues/89

**Comment by YourWishes** [comment]
Failing CRON rebuilds are the likely cause, receiving server errors (Assuming from GitHub). Cron may need auto rescheduling. Manual building works for the time being.

**Comment by YourWishes** [comment]
Closing as duplicate of https://github.com/vitasdk/vdpm/issues/89
