### ISSUE TITLE
Box2D include failure

### ISSUE THREAD

**Issue by xfangfang** [vitasdk/packages#94]
Box2D's VITABUILD file forgot to copy the Source folder.

**Comment by Rinnegatamante** [comment]
Box2D build is fine as is.

**Comment by xfangfang** [comment]
> Box2D build is fine as is.

I think it forgot to copy the header folder "Source". It only copy one header file to _$VITASDK/arm-vita-eabi/include_

but this file include other header files belong to Box2D.

https://github.com/Rinnegatamante/Box2D/blob/master/Include/Box2D.h

The file in the link is the only file in my header folder about Box2D.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/Box2D/commit/e4e218f5ec0d5e8fab5d6a8f54079066e8dc0a16

This should fix the issue.

**Comment by xfangfang** [comment]
Great~
